version: '3'
services:

  php:
    image: espena/php
    build:
      context: ./images/php
    volumes:
      - ../:/srv:rw
      - /Volumes/dashcam/Record:/videofiles:rw
    container_name: dcm-php

  postgis:
    image: espena/postgis
    build:
      context: ./images/postgis
    volumes:
      - ../:/srv:rw
      - dcm_pgsql_data:/var/lib/postgresql/data:rw
    container_name: dcm-postgis
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=dashcam
volumes:
  dcm_pgsql_data:
